### ISSUE TITLE
Asset server (webpack-dev-server)

### ISSUE THREAD

**Issue by MrBlaise** [nickjj/flask-static-digest#1]
I started working on a flask project using https://github.com/cookiecutter-flask/cookiecutter-flask as a template.

I see that Flask-Webpack is now deprecated in favour of this project. Can you give me guidance how can I achieve the same thing with this project?

Webpack already creates properly hashed files I'd like to serve them, and during development I'd like to serve them from the asset webpack server.

`stylesheet_tag` in the original project created the proper url.

Thank you!

**Comment by nickjj** [comment]
When you say "Webpack already creates properly hashed files", can you point me to the docs where this happens?

In order for your Jinja 2 templates to know about any type of hashed files, you need a third party file (a JSON manifest file usually) to map the human readable files to the hashed file name. This extension handles both creating that file and providing a `static_url_for` helper to look them up. It works exactly the same as `url_for` except it's named differently.

This new helper replaces `asset_url_for`, `stylesheet_tag` and `javascript_tag` from Flask-Webpack, and you would use `static_url_for` exactly how you use `url_for` with Flask.

**Comment by MrBlaise** [comment]
> When you say "Webpack already creates properly hashed files", can you point me to the docs where this happens?
https://webpack.js.org/guides/caching/#output-filenames using the contenthash

@nickjj Thank you I guess this file will be the manifest file that webpack generates.

**Comment by MrBlaise** [comment]
@nickjj Can I configure the library to look for my own manifest file?

**Comment by nickjj** [comment]
Creating those `contenthash` enabled files alone isn't enough, because if you only did that then you would be responsible for updating the reference to them in your Jinja 2 templates every time they changed.

I didn't see anything in the docs you linked that mentions Webpack creating its own json file that maps the regular file path to the `contenthash` version of the file. Where do you see that in docs?

**Comment by MrBlaise** [comment]
I am not really familiar with webpack and I think I confused the manifest file for a default behaviour. It was generated by Flask-Webpack probably. Sorry about that.

**Comment by MrBlaise** [comment]
```
    new ManifestRevisionPlugin(path.join(__dirname, 'gmfy', 'webpack', 'manifest.json'), {
      rootAssetPath,
      ignorePaths: ['/js', '/css'],
      extensionsRegex: /\.(ttf|eot|svg|png|jpe?g|gif|ico)$/i,
    }),
```

This is probably the piece of code that creates it.

**Comment by nickjj** [comment]
Right, that's not default Webpack behavior.

That was a custom Webpack plugin I wrote which is: https://github.com/nickjj/manifest-revision-webpack-plugin. Then Flask-Webpack used that manifest file.

But now all of that can go away.

You do not have to worry about putting the `contenthash` into the file names at the Webpack level. Instead this new Flask-Static-Digest command will do everything needed to md5 tag, gzip, create the manifest and pull it all together with `static_url_for`. It's something you can run as part of your build process after Webpack outputs its final assets into a directory.

**Comment by MrBlaise** [comment]
@nickjj Got it! Thanks! I will do that then :)

**Comment by nickjj** [comment]
Sounds like a plan.

It also works seamlessly if you don't run `flask digest compile`. If no manifest is present then `static_url_for` directly calls `url_for`. So it works in both development and production with no changes on your end.

**Comment by nickjj** [comment]
I'm going to go ahead and close this.

I've also added a migration guide to the README to move from Flask-Webpack to Flask-Static-Digest.
