### ISSUE TITLE
Faster hashing with SHA1 or xxhash

### ISSUE THREAD

**Issue by Eshaan7** [nickjj/flask-static-digest#12]
Since the hash function (md5) used in this lib is for non-cryptography purposes, wouldn't it be better to use a faster hashing algorithm like xxhash?

https://github.com/Cyan4973/xxHash

In a project with many static files, this could give a real improvement in build time.

**Comment by nickjj** [comment]
Hi,

Have you done a side by side comparison of both?

Micro benchmarks rarely show the full story. For example, Rails, Django, Phoenix and other frameworks all use md5 and some really large applications (such as GitHub) are using Rails. Their assets are tagged with md5 hashes.
