### ISSUE TITLE
static_url_for returning 500

### ISSUE THREAD

**Issue by Mitalee** [nickjj/flask-static-digest#14]
Hi Nick,

On using static_url_for for images, sometimes if an image is not available, it results in a 500 error and the entire page errors out. 

For now we have resorted to quickly changing them on the fly to url_for until the developer hunts for the image. 

Is there anything we can do such that static_url_for could return, for example, a 404 instead of 500 response, as this would help the page load without the image and with an alt-text at least.

Regards,
Mitalee

**Comment by nickjj** [comment]
Hi,

Without more details this sort of doesn't sound like it's related to `static_url_for`. Can you supply a stack trace?

`static_url_for` calls `url_for` btw. There's no custom implementation under the hood.

If there's no manifest file it it calls `return url_for(endpoint, **values)`. If there is a manifest it reads from that, looks up your file name, returns the md5 tagged version of it and then calls `return url_for(endpoint, **values)`.

In this case `endpoint` is typically `'static'` and `**values` gets unpacked to whatever you passed in, such as `filename='images/flask.png'`.

**Comment by Mitalee** [comment]
Hi,

Sure, here's a traceback. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/a7t/blueprints/blog/views.py", line 82, in post_contents
    return render_template('content.html', blogpost=blogpost)#, tags=tags)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/a7t/blueprints/blog/templates/content.html", line 5, in top-level template code
    {% set utm_blogpost_url = blogpost.url+'?utm_source=BlogPost' %}
  File "/app/a2t/templates/layouts/app.html", line 1, in top-level template code
    {% extends 'layouts/base.html' %}
  File "/app/a7t/templates/layouts/base.html", line 30, in top-level template code
    {% block other_head_content %}{% endblock %}
  File "/app/a7t/blueprints/blog/templates/content.html", line 11, in block "other_head_content"
    <meta property="og:image" content="{{ static_url_for('static', filename='images/logos/logo.svg') }}" />
  File "/usr/local/lib/python3.6/site-packages/flask_static_digest/__init__.py", line 64, in static_url_for
    return flask_url_for(endpoint, **merged_values)
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/routing.py", line 2182, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'static'. Did you forget to specify values ['filename']?
```

**Comment by nickjj** [comment]
Thanks.

Can you also include your entire manifest file as it is on the server that's causing this error?

**Comment by Mitalee** [comment]
Sent. the issue is mainly about missing static files causing the BuildError.

Thank you!

**Comment by nickjj** [comment]
I'm curious how the manifest was built too because I would have expected maybe a compile error because it wouldn't be able to md5 tag a file that doesn't exist on disk (which would be expected).

How did things get into a state where your templates were referencing files that are different than the manifest?

Also still waiting on the answer to this one:

> Also you mentioned it only sometimes returns a 500 for missing images. What happens in the other cases for missing images? Does it throw a 404 for those?

**Comment by Mitalee** [comment]
> I'm curious how the manifest was built too because I would have expected maybe a compile error because it wouldn't be able to md5 tag a file that doesn't exist on disk (which would be expected).
Never had a problem with clean and compile. In fact we would not get these problems in local development because we wouldn't be using flask-static-digest on local, so all issues would come on the production server. So we started testing all GET pages heavily with pytest, but I guess this blog page was untested.

> How did things get into a state where your templates were referencing files that are different than the manifest?
The templates are created manually by a developer, and then `clean` is run on production.. No errors so far in local, fails gracefully, so we could never catch that an image was missing. It is only on production (once `clean` and `compile` is run) that the static_url_for generates 500. 
> > Also you mentioned it only sometimes returns a 500 for missing images. What happens in the other cases for missing images? Does it throw a 404 for those?
All missing images have thrown 500 errors. We've been fixing them on the fly until now.

**Comment by nickjj** [comment]
Did you run `compile` when your templates contained image paths that didn't exist?

For example, `compile` has this code in it when it comes time to figuring out what the md5 value is:

```py
def _generate_digest(file):
    digest = None

    with open(file, "rb") as f:
        digest = hashlib.md5(f.read()).hexdigest()

    return digest
```

If you passed in a file of `some/path/that/does/not/exist.jpg` then this function would blow up because it wouldn't be able to read the file. Technically it should be impossible to ever `compile` when you have an invalid path sent into `static_url_for`. Technically as in, that was my intention :D.

Also in the email you sent, your manifest contained this line:

```
"images/logo.svg": "images/logo-2de9e9752f969ae1e2c9b92bdc60373d.svg"
```

Can you send me the manifest entry that has the broken image path being passed in? The one with `images/logos/logo.svg` that caused the 500.

**Comment by Mitalee** [comment]
> Did you run `compile` when your templates contained image paths that didn't exist?

Yes, compile ran on the shell, when the html page had the path as `images/logos/logo.svg`. It's a developer error (there's no `images/logos/logo.svg`).
> If you passed in a file of `some/path/that/does/not/exist.jpg` then this function would blow up because it wouldn't be able to read the file. Technically it should be impossible to ever `compile` when you have an invalid path sent into `static_url_for`. Technically as in, that was my intention :D.

That would be good, yes. That's exactly what we need to test everything out in local before sending it on production.
> Also in the email you sent, your manifest contained this line:
> 
> ```
> "images/logo.svg": "images/logo-2de9e9752f969ae1e2c9b92bdc60373d.svg"
> ```
> 
> Can you send me the manifest entry that has the broken image path being passed in? The one with `images/logos/logo.svg` that caused the 500.

No entry for `images/logos/logo.svg`, as there's no `logo.svg` in the `images/logos` directory. The file is present in the `images` directory itself, and that's probably how the development error came in (we intended to put `logo.svg` in the `logos` directory but ended up putting it in the `images` directory, causing this confusion and the error itself).

**Comment by nickjj** [comment]
Wait, apparently I forgot what I even coded because what I wrote in my previous comment isn't accurate. This is what I get for answering questions after crawling out of bed haha.

`compile` is going to crawl through the files on disk and md5 them, so they only get md5 tagged if they exist. It doesn't take your templates into account, so if you had an invalid path sent to `static_url_for`, that wouldn't affect `compile`.

I haven't tested this yet but I think I see what's happening:

1. You compile things and have the manifest and digested files all ready to go
2. One of the digested files is `images/logo.svg` and it's all good on disk
3. You reference `images/logos/logo.svg` (bad path) in `static_url_for`
4. `static_url_for` internally does a `self.manifest.get('images/logos/logo.svg')`
5. This fails to be looked up, and defaults to `None`
6. `static_url_for` ends up calling `url_for('static', None)`
7. Flask isn't happy and it throws a 500 because it expects a `filename`

So the fix on Flask-Static-Digest would be to have 1 extra check that says "If the lookup produces `None` then use the original undigested filename instead of `None`".

In the above case that would result in `url_for('static', 'images/logos/logo.svg')` which would then 404.

**Comment by Mitalee** [comment]
Bingo! Url_for works for us, fails silently with alt text.

**Comment by nickjj** [comment]
Thanks, I'll fix this today.

**Comment by nickjj** [comment]
I just pushed v0.1.4 which has this fix in place.

Let me know how it goes and then feel free to close this issue when you're satisfied.

Thanks for the bug report!

**Comment by Mitalee** [comment]
Totally, will get back immediately post testing. Thank you!

**Comment by nickjj** [comment]
Closing this as I'm pretty sure it's addressed. I tested it before releasing that version on a few projects.

If it still happens, feel free to re-open this issue.

**Comment by Mitalee** [comment]
Hi Nick,

Upgraded to version 0.1.4 and confirmed this issue is fixed. Thanks for the prompt upgrade!

**Comment by Mitalee** [comment]
Hi Nick,

Is there a way to test the urls in the python shell with the static_url_for option? We would like to write tests for this so that we know which repos need to be updated to the latest version.

**Comment by nickjj** [comment]
Not that I'm aware of. It's no different than `url_for` in the end. You could test against every individual file for it being a 200 that would be really tedious and personally I wouldn't do that.

Funny enough, prior to fixing the `None` issue you did have testability by rendering the page in a test and it would blow up with a 500 if it had any invalid static files. So it ended up being better than `url_for` in the end. I wonder if I should bring that behavior back as an option which defaults to 500ing, but you can turn it off so it acts like `url_for`.
