### ISSUE TITLE
a idea: dev envirienment with webpack

### ISSUE THREAD

**Issue by mouday** [nickjj/flask-static-digest#18]
```python
# -*- coding: utf-8 -*-
from urllib.parse import urljoin

from flask_static_digest import FlaskStaticDigest


class WebpackFlaskStaticDigest(FlaskStaticDigest):
    """
    FLASK_WEBPACK_DEV_HOST
    """

    def init_app(self, app):
        self.webpack_dev_host = app.config.get("FLASK_WEBPACK_DEV_HOST")
        super().init_app(app)

    def static_url_for(self, endpoint, **values):
        if self.app.debug and self.webpack_dev_host:
            return self._prepend_webpack_dev_host_url(values.get('filename'))

        return super().static_url_for(endpoint, **values)

    def _prepend_webpack_dev_host_url(self, filename):
        return urljoin(self.webpack_dev_host, filename)

```

now, i can config `FLASK_WEBPACK_DEV_HOST`  in  dev env.
```python
app.config['FLASK_WEBPACK_DEV_HOST'] = 'http://localhost:8383'
app.debug = True
```

use webpack, i can use:

1. sass to css
2. js module
3. live hot
...

i think, this a good a idea.

**Comment by nickjj** [comment]
Hi,

What makes this different than Webpack writing files out to disk that Flask serves?

**Comment by mouday** [comment]
> Hi,
> 
> What makes this different than Webpack writing files out to disk that Flask serves?

in  dev env, i impl Real time modification

3 different static file from:

1. dev:   webpack_host/main.js
2. pre-pro:  main.js
3. pro: main-[hash].js

**Comment by nickjj** [comment]
You might be able to get this behavior already by setting: `FLASK_STATIC_DIGEST_HOST_URL = "http://localhost:8383"`

That will prefix all URLs that `static_url_for` creates with that host. It's mainly used for using a CDN but it sounds like it should work for using the Webpack dev server too.

Let me know how it goes.

**Comment by mouday** [comment]
it work, thank you for tell me this method. i can write less code.

**Comment by nickjj** [comment]
Great, thanks. I'll update the docs later today to mention you can use this config option for this use case too.
