### ISSUE TITLE
has not working

### ISSUE THREAD

**Issue by daeeros** [nickjj/flask-static-digest#23]
i have code like this:

`	<script src="{{ static_url_for('static', filename='loader/loader.js') }}"></script>`

But in html page showing default name wizhout md5 name, how can i fix it?

![image](https://user-images.githubusercontent.com/34482855/124669047-67b30180-deba-11eb-835d-f6a553e7d6e1.png)

**Comment by nickjj** [comment]
Hi,

Did you run the digest command? It'll only be digested if you digest them which is normally done in production. In development by default if you don't digest it then it works like `url_for` does without the digests. But you can still run your server in development mode and digest your static files to see how it works.

**Comment by nickjj** [comment]
Going to close this as my reply likely addresses why it wasn't digested.
